---
title: '2.3: Lab'
output:
  html_document:
    df_print: paged
---
## 2.3.1

```{r}
x = c(1,6,2)
y <- c(1,4,3)
print(x)
print(y)
```
```{r}
x+y
```
```{r}
ls()
```
```{r}
rm(list=ls())
ls()
```
```{r}
x = matrix(data = c(1,2,3,4), nrow = 2, ncol = 2)
x
```
```{r}
matrix(data = c(1,2,3,4), nrow = 2, ncol = 2, byrow = T)
```
```{r}
sqrt(x)
```
```{r}
x^2
```
```{r}
x = rnorm(50)
y = x + rnorm(50, mean = 50, sd = 0.1)
cor(x,y)
```
```{r}
print(mean(y))
print(var(y))
print(sqrt(var(y)))
```
## 2.3.2

```{r}
x =rnorm(100)
y = rnorm(100)
plot(x,y, xlab = "X", ylab = "Y", main = "Random")
```
```{r}
pdf("Figure.pdf")
plot(x,y,col = "green")
dev.off()
```
```{r}
x = seq(1,10)
x
```
```{r}
x = seq(-pi, pi, length.out = 50)
x
```
```{r}
y = x
f = outer(x,y,function(x,y)cos(y)/(1+x^2))
contour(x,y,f)
```
```{r}
contour(x,y,f, nlevels = 45)
```
```{r}
fa = (f-t(f))/2
contour(x,y,fa, nlevels = 15)
```
```{r}
image(x,y,fa)
```
```{r}
persp(x,y,fa)
```
## 2.3.3

```{r}
A = matrix(1:16,4,4)
A
```
```{r}
A[2,3]
```
```{r}
A[c(1,3),c(2,4)]
```
```{r}
A[1:3,2:4]
```
```{r}
A[1:2,]
```
```{r}
A[,1:2]
```
```{r}
A[-c(1,3),]
```
```{r}
dim(A)
```
## 2.3.4

```{r}
Auto = read.table("Auto.data")
fix(Auto)
```

```{r}
Auto = read.table("Auto.data", header = T, na.strings = "?")
fix(Auto)
```

```{r}
Coll = read.csv("College.csv", header = T, na.strings = "?")
dim(Coll)
```
```{r}
Auto[1:4,]
```
```{r}
print(dim(Auto))
Auto = na.omit(Auto)
print(dim(Auto))
```
```{r}
names(Auto)
```
## 2.3.5

```{r}
plot(Auto$cylinders, Auto$mpg)
```
```{r}
attach(Auto)
plot(cylinders, mpg)
```
```{r}
cylinders = as.factor(cylinders)
plot(cylinders, mpg, col="red")
```
```{r}
plot(cylinders, mpg, col="red", varwidth = T, horizontal = T)
```
```{r}
hist(mpg)
```
```{r}
hist(mpg, col=2, breaks=15)
```
```{r}
pairs(~ mpg + displacement + horsepower + weight + acceleration)
```

plot(horsepower, mpg)
identify(horsepower, mpg, 150) #run in the console

```{r}
summary(Auto)
```
```{r}
summary(mpg)
```

